CEDULA_ADMIN=admin
CLAVE_ADMIN=123
CATEGORIA_ADMIN=Movimiento del sistema
RUTA_RESPALDO=src/main/resources/persistencia/respaldo/respaldo.xml
RUTA_PERSISTENCIA=src/main/resources/persistencia/archivos/
RUTA_LOG=src/main/resources/persistencia/log/logs.txt